<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sivaramakrishnans-Laptop.local" failures="3" tests="7" name="Surefire test" time="6.197" errors="0" timestamp="2023-02-07T16:29:18 MST">
  <testcase classname="APIAutoMation.FailingTests" name="getalldata" time="2.045">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at APIAutoMation.FailingTests.getalldata(FailingTests.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- getalldata -->
  <testcase classname="APIAutoMation.FailingTests" name="getconditionaldata" time="0.859">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;[Electricity]&amp;gt; but was:&amp;lt;[Electricity&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<[Electricity]> but was:<[Electricity>
at APIAutoMation.FailingTests.getconditionaldata(FailingTests.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- getconditionaldata -->
  <testcase classname="APIAutoMation.GetAllDataTest" name="getalldata" time="0.48"/>
  <testcase classname="APIAutoMation.GetAllDataTest" name="headerstest" time="0.497"/>
  <testcase classname="APIAutoMation.GetConditionaldataTest" name="getconditionaldata" time="0.518"/>
  <testcase classname="APIAutoMation.RecordCountTest" name="totalrecords" time="0.659"/>
  <testcase classname="APIAutoMation.DatadrivenTest" name="DatadrivenExcelTest" time="1.074">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at Utility.ExcelUtils.datadriventests(ExcelUtils.java:94)
at APIAutoMation.DatadrivenTest.DatadrivenExcelTest(DatadrivenTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- DatadrivenExcelTest -->
</testsuite> <!-- Surefire test -->
